      SUBROUTINE RMEAJJ11(J1,J2,LL,S)
      IMPLICIT DOUBLE PRECISION(A-H,O-Z)
      COMMON/GLCON/ZERO,TENTH,HALF,ONE,TWO,THREE,FOUR,SEVEN,ELEVEN,EPS
      S=ZERO
      CALL RUMTJJ(J1,LL,LQ,LV,J)
      CALL RUMTJJ(J2,LL,LQS,LVS,J1S)
      QQ=HALF
      N=2
      Q=HALF*DBLE(LQ)
      QS=HALF*DBLE(LQS)
      QM=-HALF*DBLE(HALF*(LL+1)-N)
      QMS=-HALF*DBLE(HALF*(LL+1)-(N-1))
      CALL C0T5S(QS,QMS,QQ,Q,QM,A4)
      IF(DABS(A4).LT.EPS) RETURN
      A1=DBLE(N*(LQ+1)*(J+1))
      S=DSQRT(A1)/A4
      IN=-N-1
      IF((IN/2)*2.NE.IN)S=-S
      RETURN
      END
