      SUBROUTINE RMEW1JJ(J1,J2,K1,K2,COEF)
      IMPLICIT DOUBLEPRECISION (A-H,O-Z)
      COMMON/RIBOJJ/IMPTJJ(63),IMGTJJ(63),IMPNJJ(63),IMGNJJ(63)
      DIMENSION I10(2),I01(2)
      DATA I01/6,0/
	DATA I10/0,6/
	COEF=0.00
      IF(IMPTJJ(J1) .NE. IMPTJJ(J2)) RETURN
      IF(J1 .GT. 2) RETURN
      IF(K1.EQ.0 .AND. K2.EQ.0) THEN
        COEF=-DSQRT(DBLE(2))
      ELSEIF(K1.EQ.1 .AND. K2.EQ.0) THEN
	  COEF=-DSQRT(DBLE(I10(J1)))
      ELSEIF(K1.EQ.0 .AND. K2.EQ.1) THEN
	  COEF=-DSQRT(DBLE(I01(J1)))
	ELSE
	  WRITE(0,'(A,4I5)') ' J1 J2 = ',J1,J2
	  WRITE(0,'(A)') ' ERROR IN SUB. RMEW1JJ '
	  STOP
	ENDIF
      RETURN
      END
