      SUBROUTINE WAP1JJG(K1,BK2,QM1,QM2,QM3,IK,BK,ID,BD,WA)
      IMPLICIT DOUBLEPRECISION (A-H,O-Z)
      COMMON/GLCON/ZERO,TENTH,HALF,ONE,TWO,THREE,FOUR,SEVEN,ELEVEN,EPS
      DIMENSION IK(7),BK(3),ID(7),BD(3),IBT(7),BT(3)
      WA=ZERO
      IF(IZAS1(ID(7),BD(3),IK(7),BK(3)).EQ.0)RETURN
      ENQP=ZERO
      KK1=K1*2
      KK2=BK2+BK2+TENTH*BK2
      IQ3=QM3*TWO+QM3*TENTH
      IF(ID(3).GT.37) RETURN
      IF(ITJJ3(IK,ID,KK2,BK,BD,IBT,BT,ITP,ITG,IQ3).EQ.0)RETURN
      IQM=TWO*DABS(BT(3))+TENTH
      DO 1 IT=ITP,ITG
        CALL RUMTJJ(IT,IBT(3),IBT(7),IBTT,IBT(6))
        IF(IQM.GT.IBT(7))GO TO 1
        IF(IXJTIK(KK1,IK(3),KK2,ID(6),IK(6),IBT(6)).EQ.0)GO TO 1
        IBT(1)=IT
        BT(2)=DBLE(IBT(6))/TWO
        BT(1)=DBLE(IBT(7))/TWO
        CALL A1JJ(IBT,BT,ID,BD,QM3,D1)
        IF(DABS(D1).LT.EPS)GO TO 1
        CALL W1JJG(K1,QM1,QM2,IK,BK,IBT,BT,W)
        IF(DABS(W).LT.EPS)GO TO 1
        D1=D1*W
        CALL SIXJ(KK1,IK(3),KK2,ID(6),IK(6),IBT(6),0,SI1)
        ENQP=ENQP+D1*SI1
    1 CONTINUE
      WA=ENQP*DSQRT(DBLE((KK2+1)))
      IE=KK2+IK(6)+ID(6)
      IF(((IE/4)*4).NE.IE)WA=-WA
      RETURN
      END
